[package]
name = "onerom-gen"
version = "0.1.2"
edition = "2024"
authors = ["Piers Finlayson <piers@piers.rocks>"]
license = "MIT"
description = "ROM metadata and ROM image generator for One ROM - the flexible retro ROM replacement"
repository = "https://github.com/piersfinlayson/one-rom"
homepage = "https://onerom.org"
documentation = "https://docs.rs/onerom-gen"
keywords = ["retro", "rom", "commodore", "embedded"]
categories = ["embedded", "hardware-support"]

[dependencies]
onerom-config = { version = "0.2.1" }

serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
